name       : python-yapsy
version    : 1.12.2
release    : 1
source     :
    - https://files.pythonhosted.org/packages/f1/4c/c771fbc77045a45678cdd78f57fd4006259767c363c1f884071debd200f7/Yapsy-1.12.2.tar.gz : d8113d9f9c74eacf65b4663c9c037d278c9cb273b5eee5f0e1803baeedb23f8b
license    : BSD-2-Clause-FreeBSD
homepage   : https://yapsy.sourceforge.net/
component  : programming.python
summary    : Yet another plugin system
description: |
    Yapsy is a small library implementing the core mechanisms needed to build a plugin system into a wider application.
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
